### PR TITLE
Added linux support

### PR DESCRIPTION
**Pull request by AsakuraMizu**
it works fine on my computer (Manjaro 20.1 with KDE 5.73.0)

very tricky xd

### CODE REVIEW

**Comment by subsoap** [comment]
I'm impressed that you took up this challenge! 😀

**Comment by subsoap** [comment]
Code looks like it should work though from my understanding it may only work on some versions of Linux. I am not a Linux expert though. @chaosddp are you still around / using Linux?

**Comment by britzl** [comment]
Great contribution! Regarding the threading I'd like to add that we're adding dmThread to the Defold SDK in the next release: https://github.com/defold/defold/pull/5079

It would be great if this PR could be adapted to use dmThread once that is released.

**Comment by AsakuraMizu** [comment]
> Code looks like it should work though from my understanding it may only work on some versions of Linux.

I haven't tested it, but I think it should work fine on any DE using X11.

> It would be great if this PR could be adapted to use dmThread once that is released.

Actually, it is currently not thread-safe due to some bugs of `thread.h` which i'm using :(

It has been rewritten at [phi-x:dmThread](https://github.com/phi-x/defold-clipboard/commit/da60b809a08eeed41658f2eb7005e5634f880707), but I can't test it QAQ

**Comment by AsakuraMizu** [comment]
it works now:clap:

**Comment by britzl** [comment]
This is great! Thanks.

**Pull request merged**
